[package]
name = "pirtm-engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "pirtm_engine"
path = "src/lib.rs"

[dependencies]
num-bigint = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
nalgebra = { workspace = true }
anyhow = "1.0"
hex = { workspace = true }
pirtm-monitor = { path = "../pirtm-monitor" }
goldilocks = { path = "../pirtm-goldilocks" }

[dev-dependencies]
